### ISSUE TITLE
error loading words

### ISSUE THREAD

**Issue by incantatem1** [jamespeachh/Three-Noun-Prompts#3]
followed the description step by step, but this error keeps popping up and no actual words load. can you give an example what the key is supposed to look like?

is it even possible to use this alone? i don't really understand what's meant with "synced" and "a friend", does this require me to connect my obsidian with someone else or something...? i'm confused

**Comment by jamespeachh** [comment]
Ah I found the issue and fixed it.  Would you please try uninstalling and reinstalling to insure everything is up to date now?  I also attempted to fix some of the wording in the readme, but I definitely see how that was confusing.  I included some example keys, but in my tests I was able to use any number of characters/numbers.  I would still stick to around 3-9 character string of letters.  `secretkey` specifically is a good one.  Let me know if there is anything else I can help out with

**Comment by jamespeachh** [comment]
Sorry, I just realized I did not really answer your questions:
Example key: `secretkey`(after reinstalling)
alone: Yes!  It will still work if you do not give your key to anyone else! 
There is no literal connection beyond the both people getting the same words with the same seed, so if you are using this alone you can disregard anything about sharing the key.  

Hopefully these answered your questions better than the first solution!

**Comment by incantatem1** [comment]
It seems to work now, thanks.

Could you add a toggle for keeping the prompt refresh automated or turning it off entirely?

**Comment by jamespeachh** [comment]
I will add that in for the next version!  thank you for the suggestion :)
